// Renzo for Salesforce — injects an AI message generation button into the
// Salesforce email composer.

const RENZO_API_URL = 'https://meetrenzo.com/api/ai';
const injectedTargets = new WeakSet();

function getApiKey() {
  return new Promise((resolve) => {
    chrome.storage.local.get(['renzo_api_key'], (result) => {
      resolve(result.renzo_api_key || null);
    });
  });
}

function getContactName() {
  // Try common Salesforce Lightning record-title selectors first, then
  // fall back to the page's h1, then any breadcrumb link.
  const selectors = [
    '.slds-page-header__title',
    '.slds-page-header__name-title lightning-formatted-text',
    '.slds-page-header__name-title',
    'records-highlights-details-item lightning-formatted-text',
    '[data-aura-class="forceHighlightsDetails"] lightning-formatted-text',
    'h1'
  ];
  for (const sel of selectors) {
    const el = document.querySelector(sel);
    const text = el?.textContent?.trim();
    if (text) return text;
  }
  const breadcrumb = document.querySelector('.slds-breadcrumb a, .breadcrumbs a');
  const breadcrumbText = breadcrumb?.textContent?.trim();
  if (breadcrumbText) return breadcrumbText;
  return '';
}

function findComposeBody(container) {
  return container.querySelector('textarea, [contenteditable="true"]');
}

function showToast(message) {
  const existing = document.querySelector('.renzo-toast');
  if (existing) existing.remove();
  const toast = document.createElement('div');
  toast.className = 'renzo-toast';
  toast.textContent = message;
  document.body.appendChild(toast);
  requestAnimationFrame(() => toast.classList.add('renzo-toast-visible'));
  setTimeout(() => {
    toast.classList.remove('renzo-toast-visible');
    setTimeout(() => toast.remove(), 300);
  }, 2500);
}

function showTooltip(anchor, message) {
  const existing = document.querySelector('.renzo-tooltip');
  if (existing) existing.remove();
  const tip = document.createElement('div');
  tip.className = 'renzo-tooltip';
  tip.textContent = message;
  anchor.parentElement.appendChild(tip);
  setTimeout(() => tip.remove(), 3000);
}

function setComposeValue(bodyEl, text) {
  if (bodyEl.tagName === 'TEXTAREA') {
    const setter = Object.getOwnPropertyDescriptor(window.HTMLTextAreaElement.prototype, 'value').set;
    setter.call(bodyEl, text);
    bodyEl.dispatchEvent(new Event('input', { bubbles: true }));
    bodyEl.dispatchEvent(new Event('change', { bubbles: true }));
  } else {
    bodyEl.focus();
    bodyEl.textContent = text;
    bodyEl.dispatchEvent(new Event('input', { bubbles: true }));
  }
}

async function handleGenerateClick(btn, container) {
  const apiKey = await getApiKey();
  if (!apiKey) {
    showTooltip(btn, 'Add your Renzo API key in the extension settings');
    return;
  }

  const bodyEl = findComposeBody(container);
  if (!bodyEl) return;

  const originalLabel = btn.textContent;
  btn.disabled = true;
  btn.textContent = 'Generating…';

  try {
    const contactName = getContactName();
    const res = await fetch(RENZO_API_URL, {
      method: 'POST',
      headers: {
        'Authorization': 'Bearer ' + apiKey,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        action: 'generate_simple',
        contactName,
        context: 'Salesforce email compose'
      })
    });
    const data = await res.json();
    if (!res.ok || !data.message) {
      showToast('Renzo: ' + (data.error || 'Could not generate message'));
      return;
    }
    setComposeValue(bodyEl, data.message);
    showToast('✓ Message generated by Renzo');
  } catch (e) {
    showToast('Renzo: ' + e.message);
  } finally {
    btn.disabled = false;
    btn.textContent = originalLabel;
  }
}

function injectButton(container) {
  if (injectedTargets.has(container)) return;
  if (!findComposeBody(container)) return;

  injectedTargets.add(container);

  const btn = document.createElement('button');
  btn.type = 'button';
  btn.className = 'renzo-generate-btn';
  btn.textContent = '✉ Generate with Renzo';
  btn.addEventListener('click', () => handleGenerateClick(btn, container));

  container.prepend(btn);
}

function scanForComposeWindows(root) {
  const candidates = root.querySelectorAll(
    '[class*="email"], [class*="compose"], [class*="emailBody"]'
  );
  candidates.forEach((el) => {
    if (findComposeBody(el)) injectButton(el);
  });
}

const observer = new MutationObserver((mutations) => {
  for (const mutation of mutations) {
    mutation.addedNodes.forEach((node) => {
      if (node.nodeType !== Node.ELEMENT_NODE) return;
      scanForComposeWindows(node);
      if (
        (node.className && String(node.className).match(/email|compose|emailBody/i)) &&
        findComposeBody(node)
      ) {
        injectButton(node);
      }
    });
  }
});

observer.observe(document.body, { childList: true, subtree: true });
scanForComposeWindows(document.body);
